language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t vihuvac/react-sample-app -f Dockerfile.dev .

script:
  - docker run -e CI=true vihuvac/react-sample-app npm run test
