language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t vihuvac/react-sample-app -f Dockerfile.dev .

script:
  - docker run -e CI=true vihuvac/react-sample-app npm run test

deploy:
  skip_cleanup: true
  provider: $CI_PROVIDER
  region: $CI_REGION
  app: $CI_APP
  env: $CI_ENV
  bucket_name: $CI_BUCKET_NAME
  bucket_path: $CI_BUCKET_PATH
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
