# LTS image from docker hub.
FROM node:12-alpine

# Create app directory.
WORKDIR /app

# A wildcard is used to ensure the package.json has been copied to the image.
COPY package.json /app

# Install dependencies.
RUN npm install

# Copy local files to the docker image.
COPY ./public /app/public
COPY ./src /app/src

# Start the application.
CMD ["npm", "run", "start"]
