version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./public:/app/public
      - ./src:/app/src
    restart: always
    stdin_open: true

  react-app-tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./public:/app/public
      - ./src:/app/src
    command: ['npm', 'run', 'test']
